server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri.html $uri/ /index.html;
  }

  location ~* \.(js|css|png|jpg|svg|woff2)$ {
    expires 1y;
    access_log off;
  }
}